export const metadata = { title: 'Privacy Policy — Beehive Studio' }

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#141414]">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold text-white mainFont mb-2">Privacy Policy</h1>
        <p className="text-white/40 text-sm mb-12">Last updated: May 2026</p>
        <div className="space-y-8 text-white/70 leading-relaxed">
          <section>
            <h2 className="text-white font-semibold text-lg mb-3">Information We Collect</h2>
            <p>We collect information you provide when creating an account (email address, username, bio, profile photo) and information generated by your use of the service (books, chapters, writing activity).</p>
          </section>
          <section>
            <h2 className="text-white font-semibold text-lg mb-3">How We Use Your Information</h2>
            <p>We use your information to provide and improve Beehive Studio, send transactional emails (email verification, password reset), and display your public profile and published works to other users.</p>
          </section>
          <section>
            <h2 className="text-white font-semibold text-lg mb-3">Data Storage</h2>
            <p>Your data is stored on secure servers via Neon (Postgres database) and Cloudinary (images). We do not sell your personal information to third parties.</p>
          </section>
          <section>
            <h2 className="text-white font-semibold text-lg mb-3">Contact</h2>
            <p>Questions about this policy? Email us at privacy@beehive-studio.app.</p>
          </section>
        </div>
      </div>
    </div>
  )
}
